name: Build pytcc and run unittests
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        arch: [x86, x64]
        exclude:
          # ubuntu is not available in 32bit flavuor any more
          - os: ubuntu-18.04
            arch: x86

    runs-on: ${{matrix.os}}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v1.2.0
        with:
          submodules: true

      - name: Build static libtcc and runtime library Projectfile
        shell: bash
        run: |
          declare -A OS=(
            [windows-2019]=win
            [ubuntu-18.04]=linux )
          declare -A ARCHBITS=(
            [x86]=32
            [x64]=64 )
          declare -A ARCHOPTS=(
            [windows-2019-x86]='-A Win32'
            [windows-2019-x64]='-A x64' )
          OUT_DIR=tinycc-bin/${OS[${{matrix.os}}]}${ARCHBITS[${{matrix.arch}}]}
          cmake -B $OUT_DIR ${ARCHOPTS[${{matrix.os}}-${{matrix.arch}}]}
          cmake --build $OUT_DIR --config Release

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: ${{matrix.arch}}

      - name: Build Wheel
        run: |
          python -m pip wheel -w wheels .

      - name: Run Unittests
        shell: bash
        run: |
          python -m venv venv
          . venv/*/activate
          pip install -f wheels pytcc pytest
          pytest
