name: Build pytcc and run unittests
on: [push]

jobs:
  build:

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        os: [windows-2019, ubuntu-20.04, macos-10.15]
        arch: [x86, x64]
        exclude:
          # ubuntu and macOS are not available in 32bit flavuor any more
          - os: ubuntu-20.04
            arch: x86
          - os: macos-10.15
            arch: x86

    runs-on: ${{matrix.os}}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v1.2.0
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
          architecture: ${{matrix.arch}}

      - name: Build Wheel for Manylinux2014
        if: startsWith(matrix.os, 'ubuntu')
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2014_x86_64
        with:
          pre-build-command: 'bash .github/workflows/build-libtcc.sh ${{matrix.os}} ${{matrix.arch}}'
          python-versions: '${{ fromJson(''{"3.6": "cp36-cp36m", "3.7": "cp37-cp37m", "3.8": "cp38-cp38"}'')[matrix.python] }}'
          build-requirements: cython
          pip-wheel-args: '-w ./wheels --no-deps'

      - name: Build Wheel for Windows/macOS
        if: startsWith(matrix.os, 'windows') || startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          bash .github/workflows/build-libtcc.sh  ${{matrix.os}} ${{matrix.arch}}
          python -m pip wheel -w wheels .

      - name: Run Unittests
        shell: bash
        run: |
          pip install -f wheels pytcc pytest
          pytest
